### PR TITLE
upgrade item code; now generally less specific when necessary

### PR DESCRIPTION
**Pull request by marcusklaas**
This should be specific enough for all the cases I could find. Added bonus: it's also twice as fast as the old one!

### CODE REVIEW

**Comment by JordyMoos** [comment]
I don't really get it. You just replace the first 3 positions with 0 in the if statement?

**Comment by marcusklaas** [comment]
Nope, I replace the whole itemLink with the first 3 positions ;-)

Edit:

`|H0:item:45154:21:26:26844:2:26:0:0:0:0:0:0:0:0:0:34:0:0:0:0:0|hbeech inferno staff of shock^n|h` becomes `45154/21/26`

**Comment by JordyMoos** [comment]
Ahh now i get it. But then you miss the last position (before the name) which looks like it indicates the traits strength and duration for some types.
Correct me if i am wrong

**Comment by marcusklaas** [comment]
I looked into that. I haven't been able to find a single example where the last property was different, yet the first three properties were the same.

**Comment by marcusklaas** [comment]
Woops.. it looks like you are correct.

`|H0:item:45061:283:50:26582:283:50:0:0:0:0:0:0:0:0:0:7:0:0:0:10000:0|hvoidsteel sabatons of magicka^p|h`
and
`|H0:item:45061:283:50:26580:283:50:0:0:0:0:0:0:0:0:0:9:0:0:0:10000:0|hvoidsteel sabatons of health^p|h`
are distinctly different items with the same first three properties...

**Comment by JordyMoos** [comment]
Alright the last property stands for "condition" of the item for gear and weapons (so if the enchant is full or the equipment is damaged) so that could be removed for gear and weapons.

But for potions type 7 we should be really really sure that the last property is also in there
|H0:item:30145:129:50:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:724739|hpanacea of Spell Power|h  
|H0:item:30145:129:50:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:721664|hpanacea of Spell Power|h

The values differ probably because one buff takes longer then the others (better crafting skill)

**Comment by marcusklaas** [comment]
Aaaah I didn't know :+1:

**Comment by JordyMoos** [comment]
```
Woops.. it looks like you are correct.
|H0:item:45061:283:50:26582:283:50:0:0:0:0:0:0:0:0:0:7:0:0:0:10000:0|hvoidsteel sabatons of magicka^p|h
and
|H0:item:45061:283:50:26580:283:50:0:0:0:0:0:0:0:0:0:9:0:0:0:10000:0|hvoidsteel sabatons of health^p|h
are distinctly different items with the same first three properties...
```

We can ignore the name, that is set by 26582 and 26580 (3th property after the id)
I am not sure where the 7 and 9 stand for near the end. Maybe the crafting style (nord, high elves etc)
The 10000 is decently the condition (100%) which we can ignore because you can fix and refill items

**Comment by marcusklaas** [comment]
The 7 and 9 seem to be irrelevant. Maybe it indicates how the item was acquired. Your old code didn't take it into account either.

**Comment by JordyMoos** [comment]
Look great :+1: 

I will test it tonight!

**Pull request merged**
