### PR TITLE
speedup itemcode

### PR DESCRIPTION
**Pull request by marcusklaas**
Hope this works!

### CODE REVIEW

**Comment by JordyMoos** [comment]
Thanks for removing 80% of this addons code.

I hope this works too :)

**Comment by JordyMoos** [comment]
MMm the code is not unique enough because some items do no longer give a price or show less results. We need to figure out which position we can disable

**Comment by marcusklaas** [comment]
Does that mean it is too specific? I.e. we are setting things to 0 which actually matter?

**Comment by JordyMoos** [comment]
No it means that we should set more positions to 0. But i do now know which ones yet. I will check soon :)

**Comment by marcusklaas** [comment]
Ah yes, that makes sense now :+1:

**Comment by marcusklaas** [comment]
Is it possible for some fields to be empty by the way? I did not account for that possibility. It would explain the current behaviour.

**Comment by marcusklaas** [comment]
Maybe this pattern will work:

```
(|[^:]*:[^:]*:[^:]*:[^:]*:[^:]*):[^:]*:([^:]*:[^:]*:[^:]*:[^:]*:[^:]*:[^:]*:[^:]*:[^:]*:[^:]*:[^:]*:[^:]*:[^:]*:[^:]*):[^:]*:([^:]*):(.*)
```

**Comment by JordyMoos** [comment]
This is what ZOS uses. What suggest that fields can be empty

**Comment by JordyMoos** [comment]
http://esodata.uesp.net/100010/src/libraries/utility/zo_linkhandler.lua.html#65

**Comment by marcusklaas** [comment]
Makes sense to try the new pattern then! We're also dropping the `text` field I see. Doesn't matter?

**Pull request merged**
